analytics: {}
color:
  brandColors:
    - '#dfe6de'
    - '#5b3f70'
    - '#87729d'
    - '#13140f'
    - '#8c9fad'
  brandStrength: 1
  lightness: 0.25
  rhythmicContrast: 0.8852408973034471
  saturation: 0
cta: {}
layout_spectrum: 0.6453376889694482
name: "Carrie's Lashes"
opengraph: {}
purpose: []
typography_spectrum: 0.257401
