name: "Carrie's Lashes"
favicon: null
layout_spectrum: 0.70217
typography_spectrum: 0.60085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe6de'
    - '#5b3f70'
    - '#87729d'
    - '#13140f'
    - '#8c9fad'
  brandStrength: 0.277138
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.88524
purpose: []
