name: Carrie Lashes
favicon: null
layout_spectrum: 0.6453376889694482
typography_spectrum: 0.60139
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdddd0'
    - '#b56858'
    - '#d4a89f'
    - '#d13125'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.8852408973034471
purpose: []
