analytics: {}
color:
  brandColors:
    - '#dfe6de'
    - '#5b3f70'
    - '#87729d'
    - '#13140f'
    - '#8c9fad'
  brandStrength: 0.5
  lightness: 0.25
  rhythmicContrast: 0.8852408973034471
  saturation: 0.25
cta: {}
layout_spectrum: 0.563322
name: "Carrie's Lashes"
opengraph: {}
purpose: []
typography_spectrum: 0.61858
