analytics: {}
color:
  brandColors:
    - '#dfe6de'
    - '#5b3f70'
    - '#87729d'
    - '#13140f'
    - '#8c9fad'
  brandStrength: 0.277138
  lightness: 0.25
  rhythmicContrast: 0.88524
  saturation: 0.25
cta: {}
layout_spectrum: 0.41539
name: "Carrie's Lashes"
opengraph: {}
purpose: []
typography_spectrum: 0
